version = 1

exclude_patterns = [
    "src/examples/**",
    "examples/**",
    "test/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["browser"]
  plugins = ["vue"]
  style_guide = "standard"
  dialect = "typescript"
